### ISSUE TITLE
.jsx - extention not working

### ISSUE THREAD

**Issue by thoufiq-tech** [skyran1278/js-jsx-snippets#10]
Type: <b>Bug</b>

I would like to tell about my react extention issue
When i store the file like component.jsx , It cant be working kindly fix the issue

Extension version: 11.0.1
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.10GB free)|
|Process Argv|--crash-reporter-id a4e3b906-ba0f-470c-87b5-f0c8cbc7f5de|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by skyran1278** [comment]
Apologies, I'm unable to replicate the issue you're encountering.
![image](https://github.com/skyran1278/js-jsx-snippets/assets/20672821/7bb05865-d878-414d-a2f4-ebff80f626bf)
