### ISSUE TITLE
Configuration option to not have import React on component snippet (as per react v17)?

### ISSUE THREAD

**Issue by fleps** [skyran1278/js-jsx-snippets#11]
Hi!

Would it be possible to add a configuration option to the extension so when we use any snippets to create a component it doesn't automatically add the `import React from 'react';`, as this is no longer mandatory for components?

Great extension, I tested many and yours is basically the best, specially to proper parse the component name to CamelCase regardless of the component file name.

Thanks!

**Comment by skyran1278** [comment]
Thank you. I am currently working on it and will inform you once it's released.

**Comment by skyran1278** [comment]
Hi, this feature has been launched as a pre-release version v11.1.2.

**Comment by techzealot** [comment]
> Hi, this feature has been launched as a pre-release version v11.1.2.

how to config? There are no vscode settings.
