### ISSUE TITLE
'No semicolons' setting

### ISSUE THREAD

**Issue by verbumfeit** [skyran1278/js-jsx-snippets#2]
Hey :)
Thank you for the snippets, they're ultra handy.

I don't use semicolons in my code, so I would love a setting that omits them. Simple request, but is it possible?

Thanks in advance

**Comment by skyran1278** [comment]
hi~ thank you your feedback, I will trying to do it.

**Comment by skyran1278** [comment]
Hi, this feature has been launched as a pre-release version v11.1.2.
