### ISSUE TITLE
Extension not working with .tsx files

### ISSUE THREAD

**Issue by juanhuanaco** [skyran1278/js-jsx-snippets#8]
The extension works great with js and jsx, but when i work with .tsx files it doesn't show me the snippets, did i miss some config beforehand ??

Thx in advance.

**Comment by skyran1278** [comment]
Hi @jdhqLifes, thanks for adopting this extension. Unfortunately, it doesn't support TypeScript snippets.

Alternatively, you could try installing a different extension that specifically provides code snippets for TypeScript. There are many extensions available that support TypeScript, so you may be able to find one that meets your needs.

I hope this helps. Please let me know if you have any other questions.

**Comment by juanhuanaco** [comment]
i understand thx dude, but u should remove .ts and .tsx from the "Supported languages (file extensions)" section, so it does not confuse to other devs.
Again thank you for making such a good extension 🍿😉🎊
![image](https://user-images.githubusercontent.com/67289912/209961911-5cebdd73-ce63-4c26-84f2-2cf13eee3195.png)
